[package]
name = "void_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
void_core = {path = "../void_core"}
tokio = {version = "1.36.0", features = ["sync"]}
